spring.application.name=PI_Article
spring.datasource.url=jdbc:mysql://localhost:3306/PI_Article?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.webflux.cors.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server.servlet.context-path=/PI_article
logging.level.root=INFO

# Logs détaillés pour Spring Web (contrôleurs, requêtes)
logging.level.org.springframework.web=DEBUG

# Logs pour les requêtes HTTP entrantes
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#http://localhost:8080/PI_article/swagger-ui/index.html